#!/bin/bash

echo "🔍 Environment Variables Check for Production"
echo "============================================="

echo ""
echo "📋 Frontend Environment Variables (Netlify):"
echo "--------------------------------------------"
echo "1. Go to https://app.netlify.com/"
echo "2. Select your site: rebrokerforceai"
echo "3. Go to Site settings > Environment variables"
echo "4. Verify this variable is set:"
echo "   VITE_AUTH_SERVER_URL = https://your-auth-server-domain.com"
echo ""

echo "📋 Auth Server Environment Variables:"
echo "-------------------------------------"
echo "If using Heroku, run: heroku config"
echo "If using Railway/Render, check their dashboard"
echo ""
echo "Required variables:"
echo "  - GOOGLE_CLIENT_ID"
echo "  - GOOGLE_CLIENT_SECRET"
echo "  - SESSION_SECRET"
echo "  - FRONTEND_URL=https://rebrokerforceai.netlify.app"
echo "  - BASE_URL=https://your-auth-server-domain.com"
echo "  - NODE_ENV=production"
echo ""

echo "🌐 Google OAuth Configuration:"
echo "-----------------------------"
echo "1. Go to https://console.cloud.google.com/"
echo "2. APIs & Services > Credentials"
echo "3. Edit your OAuth 2.0 Client ID"
echo "4. Verify these redirect URIs are added:"
echo "   - https://your-auth-server-domain.com/auth/google/callback"
echo "   - https://rebrokerforceai.netlify.app/auth/google/callback"
echo ""

echo "🧪 Testing Steps:"
echo "----------------"
echo "1. Visit https://rebrokerforceai.netlify.app"
echo "2. Open browser developer tools (F12)"
echo "3. Check Console tab for errors"
echo "4. Click Google Sign-In button"
echo "5. Verify redirect works properly"
echo ""

echo "🔧 Quick Fixes:"
echo "--------------"
echo "• If VITE_AUTH_SERVER_URL is undefined: Set it in Netlify dashboard"
echo "• If CORS errors: Check FRONTEND_URL in auth server"
echo "• If redirect fails: Update Google OAuth redirect URIs"
echo "• If auth server down: Check deployment logs"
