#!/bin/bash

echo "🚀 BrokerForce Google OAuth Production Setup"
echo "============================================="

echo ""
echo "📋 Prerequisites:"
echo "1. Google Cloud Console OAuth 2.0 credentials"
echo "2. Heroku CLI installed (for auth server deployment)"
echo "3. Netlify CLI installed (optional)"

echo ""
echo "🔧 Step 1: Deploy Auth Server to Heroku"
echo "----------------------------------------"
echo "1. Navigate to the auth server directory:"
echo "   cd google-login-demo"
echo ""
echo "2. Create a new Heroku app:"
echo "   heroku create your-brokerforce-auth-server"
echo ""
echo "3. Set environment variables:"
echo "   heroku config:set GOOGLE_CLIENT_ID=your_google_client_id"
echo "   heroku config:set GOOGLE_CLIENT_SECRET=your_google_client_secret"
echo "   heroku config:set SESSION_SECRET=your_secure_session_secret"
echo "   heroku config:set FRONTEND_URL=https://rebrokerforceai.netlify.app"
echo "   heroku config:set BASE_URL=https://your-brokerforce-auth-server.herokuapp.com"
echo "   heroku config:set NODE_ENV=production"
echo ""
echo "4. Deploy:"
echo "   git add ."
echo "   git commit -m 'Deploy auth server'"
echo "   git push heroku main"

echo ""
echo "🔧 Step 2: Update Google OAuth Configuration"
echo "--------------------------------------------"
echo "1. Go to https://console.cloud.google.com/"
echo "2. Navigate to APIs & Services > Credentials"
echo "3. Edit your OAuth 2.0 Client ID"
echo "4. Add these Authorized redirect URIs:"
echo "   - https://your-auth-server-domain.com/auth/google/callback"
echo "   - https://rebrokerforceai.netlify.app/auth/google/callback"

echo ""
echo "🔧 Step 3: Configure Netlify Environment Variables"
echo "--------------------------------------------------"
echo "1. Go to your Netlify dashboard"
echo "2. Navigate to Site settings > Environment variables"
echo "3. Add: VITE_AUTH_SERVER_URL = https://your-auth-server-domain.com"

echo ""
echo "🔧 Step 4: Deploy Frontend"
echo "--------------------------"
echo "1. Commit and push your changes:"
echo "   git add ."
echo "   git commit -m 'Configure for production'"
echo "   git push origin main"
echo ""
echo "2. Netlify will automatically deploy from your GitHub repository"

echo ""
echo "✅ Setup Complete!"
echo "=================="
echo "Your Google OAuth should now work on https://rebrokerforceai.netlify.app"
echo ""
echo "🔍 Troubleshooting:"
echo "- Check auth server logs: heroku logs --tail"
echo "- Verify environment variables are set correctly"
echo "- Test the health endpoint: https://your-auth-server-domain.com/health"
